### ISSUE TITLE
Generated Hash is different for each request

### ISSUE THREAD

**Issue by saisubramaniam** [phxql/argon2-jvm#21]
Hi,

It is observed that every time a string is hashed, a different hash is generated. Within the same request, verification of hash with the original string matches, but there is a difference when the same string is passed to a new request.

> SALT:d94eaa2ae725c26494853167782ab21fba7e75954e3617645ed89de92f7d294f
> Matches – verification 
> HASH:$argon2i$v=19$m=100,t=10,p=5$**cccJpI0DGNZifiGrR9RuWg$C4dwpWGpeB42A8LenhAob4K0q0K5ldrmkMM890kwZGk**

> SALT:d94eaa2ae725c26494853167782ab21fba7e75954e3617645ed89de92f7d294f
> Matches – verification 
> HASH:$argon2i$v=19$m=100,t=10,p=5$**CemoOQXnzzdO0BPh+x85UQ$q5WGNLK6YCk6FcPJbHrX+Bdu+CBNE/raL2GOJCgCYg8**

Possible reason for difference in hashes – the implementation _(BaseArgon2.class; generateSalt() method)_ generates a random salt internally for every hash.
 ```
   private byte[] generateSalt() {
        byte[] salt = new byte[saltLen];
        secureRandom.nextBytes(salt); _-- Generates a user-specified number of random bytes._
        return salt;
    }
```

Wouldnt generating a random salt every time mean that the hash will never match?

**Comment by phxql** [comment]
That is intended, every hash includes a random salt. If you want to compare the hashes, use the `verify` method, not a `String.equals`.

**Comment by saisubramaniam** [comment]
Thanks for replying, so can you tell me how to authenticate an existing user?

Should I store anything more than the hash?

**Comment by phxql** [comment]
Please take a look at the pattern in the README of the project.

**Comment by andremarcondesteixeira** [comment]
this is not clear to me as well. I did read the README, but I still don't get it. I'm not confident I can use it. I know, this is probably a DUMB question, but how does this work? I did try searching the internet about how this could possibly work, but found nothing at all. How do the verify method authenticates a user if the salt is different? And MORE IMPORTANTLY, if the salt if stored in the hashed string, then what is the point of having a salt at all? Because if the database is breached, then anyone could see the salt in the hash string. What's the point? (honest question)
