### ISSUE TITLE
Future maintenance of this repository

### ISSUE THREAD

**Issue by jaripy** [phxql/argon2-jvm#95]
I saw a couple of things that are "removed" in version 3. (e. g. [here](https://github.com/phxql/argon2-jvm/blob/master/argon2-jvm-nolibs/src/main/java/de/mkammerer/argon2/Argon2Advanced.java#L22))

When is version 3 scheduled to be released?
I would appreciate it if you could also tell me about your future maintenance schedule.

**Comment by phxql** [comment]
Hey,

there's not [that much yet](https://github.com/phxql/argon2-jvm/compare/master...develop) for version 3. That's why I didn't do the release yet. Do you need the changes? If so, I can craft a release.

Maintenance schedule: I'll fix issues if they come up, I find them interesting and I find the time. Other than that, not that much planned.

**Comment by jaripy** [comment]
Thank you for your answer.

I just wanted to confirm that there are plans for a launch in the near future, so I have no requests for improvements at this time. I have no problem with your timing of the release.

Thank you for your support.
